cd /leviathan/git/
git clone git@github.com:joshuacox/docker-chef-solo.git
git clone git@github.com:joshuacox/docker-puppet.git
git clone git@github.com:joshuacox/octossh.git
git clone git@github.com:Thalhalla/DDP.git
git clone git@github.com:joshuacox/ubuntu-nginx.git
git clone git@github.com:joshuacox/docker-ubuntu.git
git clone git@github.com:Thalhalla/dockarmaiii.git
git clone git@github.com:joshuacox/docker-chef-solo.git
git clone git@github.com:joshuacox/icingash.git
git clone git@github.com:joshuacox/docker-chef-solo.git
git clone git@github.com:joshuacox/docker-archlinux-yaourt.git
git clone git@github.com:joshuacox/steamer.git
git clone git@github.com:joshuacox/docker-chef-solo.git
git clone git@github.com:joshuacox/docker-openfire.git
git clone git@github.com:joshuacox/ddd.git
git clone git@github.com:joshuacox/docker-redmine.git
git clone git@github.com:sameersbn/docker-redmine.git
git clone git@github.com:joshuacox/docker-ansible.git
git clone git@github.com:joshuacox/docker-redmine.git
git clone git@github.com:sameersbn/docker-redmine.git
